### ISSUE TITLE
# symbol

### ISSUE THREAD

**Issue by fdagner** [mattgig/GIFT-for-Stash#11]
The # symbol in line 76 belongs at the end in the string of line 72, doesn't it? Otherwise it may appear several times in the feedback (without function), as it is a loop. You could also make a separate string for the "#".

```
antwort.innerHTML += "#[stashdrop secret\\=\"" + codes[randnum(codes.length)] + "\" text\\=\"" + pickup + "\" image]";
```

**Comment by mattgig** [comment]
Thanks for catching that.
