### ISSUE TITLE
Import codes

### ISSUE THREAD

**Issue by fdagner** [mattgig/GIFT-for-Stash#6]
An import would be a cool feature. What should the file look like, which separators do you prefer?

![grafik](https://github.com/mattgig/GIFT-for-Stash/assets/99618839/5792e6a6-7388-4209-ae22-8ad666d42730)

**Comment by mattgig** [comment]
Let's keep it simple.
One code - one line:

--- start of file ---
Vo545
z3ufB
K8feX
--- end of file ---

**Comment by fdagner** [comment]
Would it be an option to copy the shortcodes into a file? Then the value of the secrets is passed on.
--- start of file ---
[stashdrop secret="vNmte8" text="Pick up!" image]
[stashdrop secret="948pUO" text="Pick up!" image]
[stashdrop secret="GXBAFO" text="Pick up!" image]
--- end of file ---

**Comment by mattgig** [comment]
When you copy the whole code you might run into problems with the message displayed for the user to pick up a symbol. 

When the teacher uses different messages, it allows students to guess what they might get.

Therefore, you would need to extract the secret and rebuild the code with the appropriate pick up string.

**Comment by fdagner** [comment]
Yes, only the secret code is extracted. But this could indeed lead to confusion. However, copy&paste would be easier.

**Comment by fdagner** [comment]
We could also implement both formats, maybe even with automatic detection
