### ISSUE TITLE
Test question with blur effect

### ISSUE THREAD

**Issue by fdagner** [mattgig/GIFT-for-Stash#8]
It would be great if the election made it clear that something is being uncovered.
For example:
```
Wähle mich! <span style="text-shadow: #111 0 0 15px;color: transparent">geheim</span>
```

![grafik](https://github.com/mattgig/GIFT-for-Stash/assets/99618839/1c21ba8a-1009-4121-afb3-b87ab77924fb)

**Comment by mattgig** [comment]
There is a problem with the suggested feature/solution. Once the question is answered, the blurred part will still be visible in between the chosen option and the revealed item to be picked up.

**Comment by fdagner** [comment]
This is not really a problem for the members of the moodlebande :D But I admit, too much code can easily become confusing.

![grafik](https://github.com/mattgig/GIFT-for-Stash/assets/99618839/5fb3641e-62d8-4746-8161-62828a418d4b)

**Comment by fdagner** [comment]
I think this can be closed here as flexible input is now possible.

![grafik](https://github.com/mattgig/GIFT-for-Stash/assets/99618839/57ee4cfb-268f-4428-bc05-c65d57f08083)
